-   id: biber-format-check
    name: Checking bib file formatting
    entry: check-biber
    language: script
    files: '.+\.bib$'
    description: This hook uses Biber to check for incorrectly-formatted .bib files.
    types: [text]
